import { getRandomColors } from "@shared/lib/getRandomColor";
import type { CourseCardProps } from "./types";

export const COURSES_DATA: CourseCardProps[] = [
    {
        id: 'mobile-dev',
        title: 'Разработка мобильных приложений',
        shortDescription: 'Создавайте приложения для iOS и Android с нуля.',
        fullDescription: 'Полный курс по мобильной разработке. В программе: React Native, Flutter и основы Swift.',
        studyDuration: 12,
        price: '45 000 ₽',
        category: 'teens',
        level: 'novice',
        type: 'profession',
        background: getRandomColors(), // Теперь рандом при инициализации
        discount: '-10%'
    },
    {
        id: 'chess-pro',
        title: 'Шахматная стратегия: Уровень Pro',
        shortDescription: 'Для тех, кто уже знает правила и хочет побеждать в турнирах.',
        fullDescription: 'Глубокий разбор дебютов, миттельшпиля и эндшпиля. Анализ партий гроссмейстеров.',
        studyDuration: 6,
        price: '15 000 ₽',
        category: 'kids',
        level: 'pro',
        type: 'course',
        background: getRandomColors(),
    },
    {
        id: 'python-special',
        title: 'Python: Анализ данных',
        shortDescription: 'Спецкурс по работе с большими данными и нейросетями.',
        fullDescription: 'Изучаем библиотеки Pandas, NumPy и основы машинного обучения.',
        studyDuration: 3,
        price: '25 000 ₽',
        category: 'adults',
        level: 'intermediate',
        type: 'special',
        background: getRandomColors(),
        discount: 'ХИТ'
    },
    {
        id: 'web-start',
        title: 'Web-разработчик с нуля',
        shortDescription: 'Освойте HTML, CSS и JavaScript за полгода.',
        fullDescription: 'Станьте востребованным фронтенд-разработчиком. Верстка и JS.',
        studyDuration: 6,
        price: '35 000 ₽',
        category: 'teens',
        level: 'novice',
        type: 'profession',
        background: getRandomColors(),
    },
    {
        id: 'ux-ui-pro',
        title: 'Проектирование систем (UX/UI)',
        shortDescription: 'Для дизайнеров, которые хотят вырасти в Senior.',
        fullDescription: 'Работа с дизайн-системами, проведение исследований и прототипирование.',
        studyDuration: 8,
        price: '50 000 ₽',
        category: 'adults',
        level: 'pro',
        type: 'course',
        background: getRandomColors(),
        discount: '-20%'
    },
    {
        id: 'scratch-kids',
        title: 'Программирование на Scratch',
        shortDescription: 'Первые шаги в создании игр для самых маленьких.',
        fullDescription: 'Изучаем логику программирования через визуальные блоки.',
        studyDuration: 2,
        price: '10 000 ₽',
        category: 'kids',
        level: 'novice',
        type: 'course',
        background: getRandomColors(),
    },
    {
        id: 'data-engineer',
        title: 'Инженер данных',
        shortDescription: 'Построение архитектуры сбора и хранения данных.',
        fullDescription: 'Работа с SQL, Hadoop, Spark и построение ETL-процессов.',
        studyDuration: 18,
        price: '65 000 ₽',
        category: 'adults',
        level: 'pro',
        type: 'profession',
        background: getRandomColors(),
    },
    {
        id: 'game-design-special',
        title: 'Сценарии в играх',
        shortDescription: 'Узнайте, как писать истории для видеоигр.',
        fullDescription: 'Спецкурс по нарративному дизайну. Создание персонажей и квестов.',
        studyDuration: 4,
        price: '22 000 ₽',
        category: 'teens',
        level: 'intermediate',
        type: 'special',
        background: getRandomColors(),
    }
];