import { getRandomColors } from "@shared/lib/getRandomColor";
import type { CourseCardProps } from "./types";

const LOREM_LONG = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dignissim, neque sit amet aliquam cursus, ante urna porta mauris, eget venenatis risus turpis ac nisl. Aenean blandit, nulla tincidunt efficitur placerat, ante nisl auctor ipsum, in auctor mauris lacus sed nibh. Quisque id imperdiet metus, non semper dui. Phasellus pellentesque vitae leo in dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse id aliquam nunc. Sed dignissim, nibh quis dapibus dapibus, ex sapien ultricies leo, sit amet placerat arcu sem id sem.";

const generateTeachers = (prefix: string) => [
    { id: `${prefix}-t1`, name: 'Антон Болтов', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t2`, name: 'Мария Сидорова', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t3`, name: 'Иван Кузнецов', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t4`, name: 'Елена Павлова', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
];

const generateBenefits = (topic: string) => [
    { id: 'b1', icon: '🚀', title: 'Быстрый старт', description: `На курсе ${topic} мы обеспечиваем максимально глубокое погружение в материал с первых минут занятия. Это позволяет ученикам не только теоретически освоить базу, но и сразу применить полученные знания на реальных кейсах, что критически важно для закрепления навыка в долгосрочной перспективе.` },
    { id: 'b2', icon: '🧠', title: 'Развитие мышления', description: `Изучение направления ${topic} напрямую влияет на нейронные связи. Мы разработали уникальную методику, которая тренирует аналитические способности, заставляя мозг находить нестандартные решения в условиях ограниченного времени, что пригодится не только в IT, но и в повседневной жизни.` },
    { id: 'b3', icon: '🏆', title: 'Результат в портфолио', description: `По окончании обучения ${topic} у каждого студента будет готов полноценный проект. Это не просто учебная работа, а качественный кейс, выполненный по всем индустриальным стандартам, который станет весомым аргументом при поступлении в вуз или поиске первой работы в крупной компании.` }
];

const generateFaq = (topic: string) => [
    { question: `Нужен ли опыт для ${topic}?`, answer: LOREM_LONG },
    { question: `Какое оборудование требуется?`, answer: LOREM_LONG },
    { question: `Будет ли сертификат по ${topic}?`, answer: LOREM_LONG },
    { question: `Как проходят практические занятия?`, answer: LOREM_LONG }
];

const generateFeatures = (topic: string) => [
    { id: 'f1', icon: '🏆', label: `Интересные уроки по ${topic}` },
    { id: 'f2', icon: '🏆', label: 'Для взрослых и детей' },
    { id: 'f3', icon: '🏆', label: 'Обучение онлайн' },
    { id: 'f4', icon: '🏆', label: 'Проф. обучение' },
    { id: 'f5', icon: '🏆', label: 'Турниры и зачеты' },
    { id: 'f6', icon: '🏆', label: 'Сертификат GM' },
];

export const COURSES_DATA: CourseCardProps[] = [
    // --- KIDS-FILTER (14 курсов) ---
    { id: 'k1', title: 'Лего-роботы', shortDescription: 'Первые шаги в робототехнике.', fullDescription: 'Погружение в инженерию с LEGO Education.', aboutDescription: 'Робототехника — это отличная идея для развития инженерного мышления. Игра дает полезные в жизни навыки: учит побеждать и проигрывать, развивает творческие способности.', studyDuration: 2, price: '12 000 ₽', category: 'kids-filter', tag: 'robotic', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Лего-роботы'), teachers: generateTeachers('k1'), faq: generateFaq('Лего-роботы'), features: generateFeatures('Робототехнике') },
    { id: 'k2', title: 'Scratch Master', shortDescription: 'Создание игр без кода.', fullDescription: 'Визуальное программирование для детей.', aboutDescription: 'Scratch учит мыслить системно и творчески. Это лучший способ войти в мир IT, создавая свои первые интерактивные истории и игры.', studyDuration: 3, price: '15 000 ₽', category: 'kids-filter', tag: 'game-dev', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Scratch'), teachers: generateTeachers('k2'), faq: generateFaq('Scratch'), features: generateFeatures('Scratch') },
    { id: 'k3', title: 'Python Kids', shortDescription: 'Код в игровом формате.', fullDescription: 'Основы Python для самых маленьких.', aboutDescription: 'Python — самый востребованный язык. Мы учим детей программировать, используя понятные примеры и увлекательные задачи.', studyDuration: 6, price: '22 000 ₽', category: 'kids-filter', tag: 'programming', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Python'), teachers: generateTeachers('k3'), faq: generateFaq('Python'), features: generateFeatures('Python') },
    { id: 'k4', title: 'Minecraft Java', shortDescription: 'Моды своими руками.', fullDescription: 'Пишем скрипты внутри игры.', aboutDescription: 'Любимая игра становится образовательной платформой. Учимся Java-разработке, изменяя мир Minecraft под свои правила.', studyDuration: 12, price: '35 000 ₽', category: 'kids-filter', tag: 'java', level: 'intermediate', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Java Minecraft'), teachers: generateTeachers('k4'), faq: generateFaq('Java Minecraft'), features: generateFeatures('Minecraft') },
    { id: 'k5', title: 'YouTube Start', shortDescription: 'Стань блогером.', fullDescription: 'Монтаж и работа в кадре.', aboutDescription: 'Развиваем харизму и технические навыки. Как создать канал, который будет интересен тысячам подписчиков.', studyDuration: 4, price: '18 000 ₽', category: 'kids-filter', tag: 'blogging', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('YouTube'), teachers: generateTeachers('k5'), faq: generateFaq('YouTube'), features: generateFeatures('YouTube') },
    { id: 'k6', title: 'Chess Junior', shortDescription: 'Турнирная база.', fullDescription: 'Шахматная стратегия и тактика.', aboutDescription: 'Шахматы развивают интеллект и усидчивость. Мы готовим детей к их первым серьезным победам за доской.', studyDuration: 5, price: '10 000 ₽', category: 'kids-filter', tag: 'chess', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Шахматы'), teachers: generateTeachers('k6'), faq: generateFaq('Шахматы'), features: generateFeatures('Шахматам') },
    { id: 'k7', title: 'Robotics Pro', shortDescription: 'Сложные механизмы.', fullDescription: 'Работа с датчиками и Arduino.', aboutDescription: 'Переходим на новый уровень: конструируем роботов, управляемых через микроконтроллеры и сложные датчики.', studyDuration: 8, price: '28 000 ₽', category: 'kids-filter', tag: 'robotic', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Arduino'), teachers: generateTeachers('k7'), faq: generateFaq('Arduino'), features: generateFeatures('Arduino') },
    { id: 'k8', title: 'Unity Kids', shortDescription: '3D Миры.', fullDescription: 'Создание объемных игр на движке.', aboutDescription: 'Профессиональный инструмент в руках ребенка. Делаем первые 3D платформеры и шутеры на Unity.', studyDuration: 10, price: '32 000 ₽', category: 'kids-filter', tag: 'game-dev', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Unity'), teachers: generateTeachers('k8'), faq: generateFaq('Unity'), features: generateFeatures('Unity') },
    { id: 'k9', title: 'Soft Skills Kids', shortDescription: 'Лидерство.', fullDescription: 'Учимся работать в команде.', aboutDescription: 'Навыки общения и эмоциональный интеллект. Учим детей договариваться и достигать целей вместе.', studyDuration: 2, price: '8 000 ₽', category: 'kids-filter', tag: 'soft-skills', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Soft Skills'), teachers: generateTeachers('k9'), faq: generateFaq('Soft Skills'), features: generateFeatures('Soft Skills') },
    { id: 'k10', title: 'Digital Art', shortDescription: 'Рисование на планшете.', fullDescription: 'Основы цифровой живописи.', aboutDescription: 'Превращаем гаджет в холст. Учим основам композиции, цвета и света в цифровом пространстве.', studyDuration: 3, price: '12 000 ₽', category: 'kids-filter', tag: 'multimedia', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Art'), teachers: generateTeachers('k10'), faq: generateFaq('Art'), features: generateFeatures('Art') },
    { id: 'k11', title: 'Mobile Apps Kids', shortDescription: 'Первое приложение.', fullDescription: 'Создание простых утилит.', aboutDescription: 'Как устроены приложения в твоем телефоне? Учимся создавать полезные программы для Android.', studyDuration: 6, price: '20 000 ₽', category: 'kids-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Mobile Apps'), teachers: generateTeachers('k11'), faq: generateFaq('Mobile Apps'), features: generateFeatures('Mobile Apps') },
    { id: 'k12', title: '3D Modeling', shortDescription: 'Герои мультиков.', fullDescription: 'Моделирование в Blender.', aboutDescription: 'От кубика до сложного персонажа. Учим детей создавать 3D объекты для игр и анимации.', studyDuration: 5, price: '19 000 ₽', category: 'kids-filter', tag: 'multimedia', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Blender'), teachers: generateTeachers('k12'), faq: generateFaq('Blender'), features: generateFeatures('Blender') },
    { id: 'k13', title: 'C# Junior', shortDescription: 'Основы языка.', fullDescription: 'Базовый синтаксис C#.', aboutDescription: 'Первое знакомство с мощным языком разработки. База для будущего геймдева и системного кода.', studyDuration: 4, price: '16 000 ₽', category: 'kids-filter', tag: 'programming', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('C#'), teachers: generateTeachers('k13'), faq: generateFaq('C#'), features: generateFeatures('C#') },
    { id: 'k14', title: 'Logic Games', shortDescription: 'Головоломки.', fullDescription: 'Развитие математического ума.', aboutDescription: 'Прокачиваем логику через увлекательные квесты и математические загадки.', studyDuration: 2, price: '7 000 ₽', category: 'kids-filter', tag: 'soft-skills', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Logic'), teachers: generateTeachers('k14'), faq: generateFaq('Logic'), features: generateFeatures('Logic') },

    // --- TEENS-FILTER (14 курсов) ---
    { id: 't1', title: 'Frontend Pro', shortDescription: 'Верстка и React.', fullDescription: 'Стань востребованным веб-разработчиком.', aboutDescription: 'Создавай современные интерфейсы. Мы учим верстке, JS и React на реальных бизнес-кейсах.', studyDuration: 12, price: '45 000 ₽', category: 'teens-filter', tag: 'web', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Frontend'), teachers: generateTeachers('t1'), faq: generateFaq('Frontend'), features: generateFeatures('Frontend') },
    { id: 't2', title: 'Python Backend', shortDescription: 'Серверная логика.', fullDescription: 'Разработка на самом популярном языке.', aboutDescription: 'Как работают сайты "под капотом". Пишем серверную часть сложных веб-приложений.', studyDuration: 8, price: '30 000 ₽', category: 'teens-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Backend'), teachers: generateTeachers('t2'), faq: generateFaq('Backend'), features: generateFeatures('Backend') },
    { id: 't3', title: 'iOS Swift Pro', shortDescription: 'Apple экосистема.', fullDescription: 'Разработка под iPhone и iPad.', aboutDescription: 'Освой Swift и начни создавать нативные приложения для экосистемы Apple.', studyDuration: 14, price: '55 000 ₽', category: 'teens-filter', tag: 'mobile', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('iOS'), teachers: generateTeachers('t3'), faq: generateFaq('iOS'), features: generateFeatures('iOS') },
    { id: 't4', title: 'C++ Game Dev', shortDescription: 'Системный код.', fullDescription: 'Программирование игровых движков.', aboutDescription: 'Для тех, кто хочет создавать Unreal Engine проекты и высокопроизводительный код.', studyDuration: 10, price: '42 000 ₽', category: 'teens-filter', tag: 'applied', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('C++'), teachers: generateTeachers('t4'), faq: generateFaq('C++'), features: generateFeatures('C++') },
    { id: 't5', title: 'UX/UI Teens', shortDescription: 'Интерфейсы.', fullDescription: 'Дизайн сайтов и мобильных приложений.', aboutDescription: 'Учимся проектировать удобные интерфейсы, которые решают задачи пользователей.', studyDuration: 6, price: '25 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('UX/UI'), teachers: generateTeachers('t5'), faq: generateFaq('UX/UI'), features: generateFeatures('UX/UI') },
    { id: 't6', title: 'Blender 3D Art', shortDescription: 'Графика и свет.', fullDescription: 'Создание реалистичных 3D моделей.', aboutDescription: 'Стань 3D художником. От моделирования до рендера сложных визуальных сцен.', studyDuration: 5, price: '20 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('3D Art'), teachers: generateTeachers('t6'), faq: generateFaq('3D Art'), features: generateFeatures('3D Art') },
    { id: 't7', title: 'Cyber Security', shortDescription: 'Этичный хакинг.', fullDescription: 'Защита сетей и данных.', aboutDescription: 'Как защитить информацию в цифровом мире. Основы кибербезопасности и криптографии.', studyDuration: 9, price: '40 000 ₽', category: 'teens-filter', tag: 'applied', level: 'pro', type: 'special', background: getRandomColors(), benefits: generateBenefits('Security'), teachers: generateTeachers('t7'), faq: generateFaq('Security'), features: generateFeatures('Security') },
    { id: 't8', title: 'SMM Branding', shortDescription: 'Твой личный бренд.', fullDescription: 'Раскрутка в социальных сетях.', aboutDescription: 'Стратегии продвижения и контент-планирование для современных медиа.', studyDuration: 3, price: '12 000 ₽', category: 'teens-filter', tag: 'blogging', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('SMM'), teachers: generateTeachers('t8'), faq: generateFaq('SMM'), features: generateFeatures('SMM') },
    { id: 't9', title: 'Unity Engine Pro', shortDescription: 'Сложная логика.', fullDescription: 'Разработка на профессиональном уровне.', aboutDescription: 'Создаем игры мирового уровня на самом популярном кроссплатформенном движке.', studyDuration: 11, price: '38 000 ₽', category: 'teens-filter', tag: 'game-dev', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Unity Pro'), teachers: generateTeachers('t9'), faq: generateFaq('Unity Pro'), features: generateFeatures('Unity') },
    { id: 't10', title: 'Web Design Intro', shortDescription: 'Дизайн лендингов.', fullDescription: 'Основы типографики и верстки.', aboutDescription: 'Как сделать сайт, который продает. База веб-дизайна для начинающих.', studyDuration: 4, price: '18 000 ₽', category: 'teens-filter', tag: 'web', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Web Design'), teachers: generateTeachers('t10'), faq: generateFaq('Web Design'), features: generateFeatures('Web Design') },
    { id: 't11', title: 'Kotlin Android', shortDescription: 'Современный Android.', fullDescription: 'Нативная мобильная разработка.', aboutDescription: 'Программируй под Android на языке Kotlin — стандарте современной разработки.', studyDuration: 12, price: '48 000 ₽', category: 'teens-filter', tag: 'mobile', level: 'intermediate', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Kotlin'), teachers: generateTeachers('t11'), faq: generateFaq('Kotlin'), features: generateFeatures('Kotlin') },
    { id: 't12', title: 'Competitive Code', shortDescription: 'Алгоритмы.', fullDescription: 'Подготовка к олимпиадам.', aboutDescription: 'Сложные алгоритмы и структуры данных для тех, кто хочет в BigTech.', studyDuration: 7, price: '26 000 ₽', category: 'teens-filter', tag: 'programming', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Algorithms'), teachers: generateTeachers('t12'), faq: generateFaq('Algorithms'), features: generateFeatures('Алгоритмам') },
    { id: 't13', title: 'VFX & Montage', shortDescription: 'Спецэффекты.', fullDescription: 'Монтаж видео и постобработка.', aboutDescription: 'Киноэффекты своими руками. Магия видеомонтажа в профессиональном софте.', studyDuration: 5, price: '22 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'intermediate', type: 'special', background: getRandomColors(), benefits: generateBenefits('VFX'), teachers: generateTeachers('t13'), faq: generateFaq('VFX'), features: generateFeatures('VFX') },
    { id: 't14', title: 'Database SQL', shortDescription: 'Сила данных.', fullDescription: 'Управление большими объемами информации.', aboutDescription: 'Базы данных — фундамент любого IT-продукта. Учимся работать с SQL на профи-уровне.', studyDuration: 4, price: '16 000 ₽', category: 'teens-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('SQL'), teachers: generateTeachers('t14'), faq: generateFaq('SQL'), features: generateFeatures('SQL') },

    // --- ADULTS-FILTER (12 курсов) ---
    { id: 'a1', title: 'QA Automation', shortDescription: 'Автотесты Java.', fullDescription: 'Стань востребованным QA-инженером.', aboutDescription: 'Качество кода — залог успеха. Учим автоматизировать тестирование сложных систем.', studyDuration: 6, price: '48 000 ₽', category: 'adults-filter', tag: 'testing', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('QA'), teachers: generateTeachers('a1'), faq: generateFaq('QA'), features: generateFeatures('QA') },
    { id: 'a2', title: 'Digital Marketing', shortDescription: 'Управляй трафиком.', fullDescription: 'Комплексный курс по маркетингу.', aboutDescription: 'Как привлечь клиента в современном мире. Весь цикл продвижения от SEO до SMM.', studyDuration: 4, price: '32 000 ₽', category: 'adults-filter', tag: 'marketing', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Marketing'), teachers: generateTeachers('a2'), faq: generateFaq('Marketing'), features: generateFeatures('Маркетингу') },
    { id: 'a3', title: 'VR/AR Developer', shortDescription: 'Метавселенные.', fullDescription: 'Разработка виртуальной реальности.', aboutDescription: 'Создавай новые миры. Весь стек разработки для виртуальной и дополненной реальности.', studyDuration: 9, price: '45 000 ₽', category: 'adults-filter', tag: 'unity', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('VR/AR'), teachers: generateTeachers('a3'), faq: generateFaq('VR/AR'), features: generateFeatures('VR/AR') },
    { id: 'a4', title: 'Java Architect', shortDescription: 'Enterprise системы.', fullDescription: 'Проектирование сложных платформ.', aboutDescription: 'Для тех, кто хочет строить архитектуру высоконагруженных банковских систем.', studyDuration: 18, price: '75 000 ₽', category: 'adults-filter', tag: 'java', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Java Architect'), teachers: generateTeachers('a4'), faq: generateFaq('Java Architect'), features: generateFeatures('Java Architect') },
    { id: 'a5', title: 'Product UI/UX', shortDescription: 'Дизайн систем.', fullDescription: 'Дизайн для крупных продуктов.', aboutDescription: 'Как мыслить продуктово и создавать дизайн, который действительно работает.', studyDuration: 7, price: '38 000 ₽', category: 'adults-filter', tag: 'design', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Product Design'), teachers: generateTeachers('a5'), faq: generateFaq('Product Design'), features: generateFeatures('UX/UI Design') },
    { id: 'a6', title: 'Python DS Pro', shortDescription: 'Data Science.', fullDescription: 'Анализ данных и нейросети.', aboutDescription: 'Данные — это новая нефть. Учим добывать из них пользу с помощью нейросетей.', studyDuration: 12, price: '58 000 ₽', category: 'adults-filter', tag: 'python', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Data Science'), teachers: generateTeachers('a6'), faq: generateFaq('Data Science'), features: generateFeatures('Data Science') },
    { id: 'a7', title: 'SEO Lead', shortDescription: 'Топ в Google.', fullDescription: 'Вывод сайтов на первые позиции.', aboutDescription: 'Весь комплекс работ по поисковой оптимизации для профессионалов.', studyDuration: 3, price: '20 000 ₽', category: 'adults-filter', tag: 'marketing', level: 'intermediate', type: 'special', background: getRandomColors(), benefits: generateBenefits('SEO'), teachers: generateTeachers('a7'), faq: generateFaq('SEO'), features: generateFeatures('SEO') },
    { id: 'a8', title: 'Manual QA', shortDescription: 'Старт в тестировании.', fullDescription: 'Ручное тестирование с нуля.', aboutDescription: 'Простой вход в IT. Учимся искать ошибки и гарантировать качество продукта.', studyDuration: 2, price: '15 000 ₽', category: 'adults-filter', tag: 'testing', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Manual QA'), teachers: generateTeachers('a8'), faq: generateFaq('Manual QA'), features: generateFeatures('Тестированию') },
    { id: 'a9', title: 'Node.js Backend', shortDescription: 'JS Сервер.', fullDescription: 'Разработка на JavaScript со стороны сервера.', aboutDescription: 'Создавай быстрые серверные решения на самом динамичном стеке технологий.', studyDuration: 10, price: '42 000 ₽', category: 'adults-filter', tag: 'software', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Node.js'), teachers: generateTeachers('a9'), faq: generateFaq('Node.js'), features: generateFeatures('Node.js') },
    { id: 'a10', title: 'iOS Lead', shortDescription: 'Управление командой.', fullDescription: 'Комплексная разработка под Apple.', aboutDescription: 'Профессиональный уровень мобильной разработки и лидерство в команде.', studyDuration: 15, price: '65 000 ₽', category: 'adults-filter', tag: 'ios', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('iOS Lead'), teachers: generateTeachers('a10'), faq: generateFaq('iOS Lead'), features: generateFeatures('iOS Lead') },
    { id: 'a11', title: 'Enterprise Spring', shortDescription: 'Microservices.', fullDescription: 'Сложные системы на Spring Boot.', aboutDescription: 'Промышленный стандарт бэкенд-разработки. База для работы в финтехе.', studyDuration: 11, price: '50 000 ₽', category: 'adults-filter', tag: 'java', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Spring'), teachers: generateTeachers('a11'), faq: generateFaq('Spring'), features: generateFeatures('Spring Boot') },
    { id: 'a12', title: 'UX Research', shortDescription: 'Поведение юзера.', fullDescription: 'Исследования и аналитика.', aboutDescription: 'Как понять пользователя и превратить эти знания в качественные интерфейсы.', studyDuration: 2, price: '12 000 ₽', category: 'adults-filter', tag: 'design', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Research'), teachers: generateTeachers('a12'), faq: generateFaq('Research'), features: generateFeatures('UX Research') },
];