import { getRandomColors } from "@shared/lib/getRandomColor";
import type { CourseCardProps } from "./types";

const LOREM_LONG = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dignissim, neque sit amet aliquam cursus, ante urna porta mauris, eget venenatis risus turpis ac nisl. Aenean blandit, nulla tincidunt efficitur placerat, ante nisl auctor ipsum, in auctor mauris lacus sed nibh. Quisque id imperdiet metus, non semper dui. Phasellus pellentesque vitae leo in dapibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse id aliquam nunc. Sed dignissim, nibh quis dapibus dapibus, ex sapien ultricies leo, sit amet placerat arcu sem id sem.";

const generateTeachers = (prefix: string) => [
    { id: `${prefix}-t1`, name: 'Антон Болтов', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t2`, name: 'Мария Сидорова', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t3`, name: 'Иван Кузнецов', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
    { id: `${prefix}-t4`, name: 'Елена Павлова', position: 'Выпускница Гарвардского Университета. Более 10 лет играет в шахматы и участвует в турнирах.', photo: 'FutureAcademyIcons/person.jpg' },
];

const generateBenefits = (topic: string) => [
    { id: 'b1', icon: '🚀', title: 'Быстрый старт', description: `На курсе ${topic} мы обеспечиваем максимально глубокое погружение в материал с первых минут занятия. Это позволяет ученикам не только теоретически освоить базу, но и сразу применить полученные знания на реальных кейсах, что критически важно для закрепления навыка в долгосрочной перспективе.` },
    { id: 'b2', icon: '🧠', title: 'Развитие мышления', description: `Изучение направления ${topic} напрямую влияет на нейронные связи. Мы разработали уникальную методику, которая тренирует аналитические способности, заставляя мозг находить нестандартные решения в условиях ограниченного времени, что пригодится не только в IT, но и в повседневной жизни.` },
    { id: 'b3', icon: '🏆', title: 'Результат в портфолио', description: `По окончании обучения ${topic} у каждого студента будет готов полноценный проект. Это не просто учебная работа, а качественный кейс, выполненный по всем индустриальным стандартам, который станет весомым аргументом при поступлении в вуз или поиске первой работы в крупной компании.` }
];

const generateFaq = (topic: string) => [
    { question: `Нужен ли опыт для ${topic}?`, answer: LOREM_LONG },
    { question: `Какое оборудование требуется?`, answer: LOREM_LONG },
    { question: `Будет ли сертификат по ${topic}?`, answer: LOREM_LONG },
    { question: `Как проходят практические занятия?`, answer: LOREM_LONG }
];

export const COURSES_DATA: CourseCardProps[] = [
    // --- KIDS-FILTER (14 курсов) ---
    { id: 'k1', title: 'Лего-роботы', shortDescription: 'Первые шаги в робототехнике.', fullDescription: 'Погружение в инженерию с LEGO Education.', studyDuration: 2, price: '12 000 ₽', category: 'kids-filter', tag: 'robotic', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Лего-роботы'), teachers: generateTeachers('k1'), faq: generateFaq('Лего-роботы') },
    { id: 'k2', title: 'Scratch Master', shortDescription: 'Создание игр без кода.', fullDescription: 'Визуальное программирование для детей.', studyDuration: 3, price: '15 000 ₽', category: 'kids-filter', tag: 'game-dev', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Scratch'), teachers: generateTeachers('k2'), faq: generateFaq('Scratch') },
    { id: 'k3', title: 'Python Kids', shortDescription: 'Код в игровом формате.', fullDescription: 'Основы Python для самых маленьких.', studyDuration: 6, price: '22 000 ₽', category: 'kids-filter', tag: 'programming', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Python'), teachers: generateTeachers('k3'), faq: generateFaq('Python') },
    { id: 'k4', title: 'Minecraft Java', shortDescription: 'Моды своими руками.', fullDescription: 'Пишем скрипты внутри игры.', studyDuration: 12, price: '35 000 ₽', category: 'kids-filter', tag: 'java', level: 'intermediate', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Java Minecraft'), teachers: generateTeachers('k4'), faq: generateFaq('Java Minecraft') },
    { id: 'k5', title: 'YouTube Start', shortDescription: 'Стань блогером.', fullDescription: 'Монтаж и работа в кадре.', studyDuration: 4, price: '18 000 ₽', category: 'kids-filter', tag: 'blogging', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('YouTube'), teachers: generateTeachers('k5'), faq: generateFaq('YouTube') },
    { id: 'k6', title: 'Chess Junior', shortDescription: 'Турнирная база.', fullDescription: 'Шахматная стратегия и тактика.', studyDuration: 5, price: '10 000 ₽', category: 'kids-filter', tag: 'chess', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Шахматы'), teachers: generateTeachers('k6'), faq: generateFaq('Шахматы') },
    { id: 'k7', title: 'Robotics Pro', shortDescription: 'Сложные механизмы.', fullDescription: 'Работа с датчиками и Arduino.', studyDuration: 8, price: '28 000 ₽', category: 'kids-filter', tag: 'robotic', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Arduino'), teachers: generateTeachers('k7'), faq: generateFaq('Arduino') },
    { id: 'k8', title: 'Unity Kids', shortDescription: '3D Миры.', fullDescription: 'Создание объемных игр на движке.', studyDuration: 10, price: '32 000 ₽', category: 'kids-filter', tag: 'game-dev', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Unity'), teachers: generateTeachers('k8'), faq: generateFaq('Unity') },
    { id: 'k9', title: 'Soft Skills Kids', shortDescription: 'Лидерство.', fullDescription: 'Учимся работать в команде.', studyDuration: 2, price: '8 000 ₽', category: 'kids-filter', tag: 'soft-skills', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Soft Skills'), teachers: generateTeachers('k9'), faq: generateFaq('Soft Skills') },
    { id: 'k10', title: 'Digital Art', shortDescription: 'Рисование на планшете.', fullDescription: 'Основы цифровой живописи.', studyDuration: 3, price: '12 000 ₽', category: 'kids-filter', tag: 'multimedia', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Art'), teachers: generateTeachers('k10'), faq: generateFaq('Art') },
    { id: 'k11', title: 'Mobile Apps Kids', shortDescription: 'Первое приложение.', fullDescription: 'Создание простых утилит.', studyDuration: 6, price: '20 000 ₽', category: 'kids-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Mobile Apps'), teachers: generateTeachers('k11'), faq: generateFaq('Mobile Apps') },
    { id: 'k12', title: '3D Modeling', shortDescription: 'Герои мультиков.', fullDescription: 'Моделирование в Blender.', studyDuration: 5, price: '19 000 ₽', category: 'kids-filter', tag: 'multimedia', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Blender'), teachers: generateTeachers('k12'), faq: generateFaq('Blender') },
    { id: 'k13', title: 'C# Junior', shortDescription: 'Основы языка.', fullDescription: 'Базовый синтаксис C#.', studyDuration: 4, price: '16 000 ₽', category: 'kids-filter', tag: 'programming', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('C#'), teachers: generateTeachers('k13'), faq: generateFaq('C#') },
    { id: 'k14', title: 'Logic Games', shortDescription: 'Головоломки.', fullDescription: 'Развитие математического ума.', studyDuration: 2, price: '7 000 ₽', category: 'kids-filter', tag: 'soft-skills', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Logic'), teachers: generateTeachers('k14'), faq: generateFaq('Logic') },

    // --- TEENS-FILTER (14 курсов) ---
    { id: 't1', title: 'Frontend Pro', shortDescription: 'Верстка и React.', fullDescription: 'Стань востребованным веб-разработчиком.', studyDuration: 12, price: '45 000 ₽', category: 'teens-filter', tag: 'web', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Frontend'), teachers: generateTeachers('t1'), faq: generateFaq('Frontend') },
    { id: 't2', title: 'Python Backend', shortDescription: 'Серверная логика.', fullDescription: 'Разработка на самом популярном языке.', studyDuration: 8, price: '30 000 ₽', category: 'teens-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Backend'), teachers: generateTeachers('t2'), faq: generateFaq('Backend') },
    { id: 't3', title: 'iOS Swift Pro', shortDescription: 'Apple экосистема.', fullDescription: 'Разработка под iPhone и iPad.', studyDuration: 14, price: '55 000 ₽', category: 'teens-filter', tag: 'mobile', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('iOS'), teachers: generateTeachers('t3'), faq: generateFaq('iOS') },
    { id: 't4', title: 'C++ Game Dev', shortDescription: 'Системный код.', fullDescription: 'Программирование игровых движков.', studyDuration: 10, price: '42 000 ₽', category: 'teens-filter', tag: 'applied', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('C++'), teachers: generateTeachers('t4'), faq: generateFaq('C++') },
    { id: 't5', title: 'UX/UI Teens', shortDescription: 'Интерфейсы.', fullDescription: 'Дизайн сайтов и мобильных приложений.', studyDuration: 6, price: '25 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('UX/UI'), teachers: generateTeachers('t5'), faq: generateFaq('UX/UI') },
    { id: 't6', title: 'Blender 3D Art', shortDescription: 'Графика и свет.', fullDescription: 'Создание реалистичных 3D моделей.', studyDuration: 5, price: '20 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('3D Art'), teachers: generateTeachers('t6'), faq: generateFaq('3D Art') },
    { id: 't7', title: 'Cyber Security', shortDescription: 'Этичный хакинг.', fullDescription: 'Защита сетей и данных.', studyDuration: 9, price: '40 000 ₽', category: 'teens-filter', tag: 'applied', level: 'pro', type: 'special', background: getRandomColors(), benefits: generateBenefits('Security'), teachers: generateTeachers('t7'), faq: generateFaq('Security') },
    { id: 't8', title: 'SMM Branding', shortDescription: 'Твой личный бренд.', fullDescription: 'Раскрутка в социальных сетях.', studyDuration: 3, price: '12 000 ₽', category: 'teens-filter', tag: 'blogging', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('SMM'), teachers: generateTeachers('t8'), faq: generateFaq('SMM') },
    { id: 't9', title: 'Unity Engine Pro', shortDescription: 'Сложная логика.', fullDescription: 'Разработка на профессиональном уровне.', studyDuration: 11, price: '38 000 ₽', category: 'teens-filter', tag: 'game-dev', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Unity Pro'), teachers: generateTeachers('t9'), faq: generateFaq('Unity Pro') },
    { id: 't10', title: 'Web Design Intro', shortDescription: 'Дизайн лендингов.', fullDescription: 'Основы типографики и верстки.', studyDuration: 4, price: '18 000 ₽', category: 'teens-filter', tag: 'web', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Web Design'), teachers: generateTeachers('t10'), faq: generateFaq('Web Design') },
    { id: 't11', title: 'Kotlin Android', shortDescription: 'Современный Android.', fullDescription: 'Нативная мобильная разработка.', studyDuration: 12, price: '48 000 ₽', category: 'teens-filter', tag: 'mobile', level: 'intermediate', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Kotlin'), teachers: generateTeachers('t11'), faq: generateFaq('Kotlin') },
    { id: 't12', title: 'Competitive Code', shortDescription: 'Алгоритмы.', fullDescription: 'Подготовка к олимпиадам.', studyDuration: 7, price: '26 000 ₽', category: 'teens-filter', tag: 'programming', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Algorithms'), teachers: generateTeachers('t12'), faq: generateFaq('Algorithms') },
    { id: 't13', title: 'VFX & Montage', shortDescription: 'Спецэффекты.', fullDescription: 'Монтаж видео и постобработка.', studyDuration: 5, price: '22 000 ₽', category: 'teens-filter', tag: 'graphics', level: 'intermediate', type: 'special', background: getRandomColors(), benefits: generateBenefits('VFX'), teachers: generateTeachers('t13'), faq: generateFaq('VFX') },
    { id: 't14', title: 'Database SQL', shortDescription: 'Сила данных.', fullDescription: 'Управление большими объемами информации.', studyDuration: 4, price: '16 000 ₽', category: 'teens-filter', tag: 'programming', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('SQL'), teachers: generateTeachers('t14'), faq: generateFaq('SQL') },

    // --- ADULTS-FILTER (12 курсов) ---
    { id: 'a1', title: 'QA Automation', shortDescription: 'Автотесты Java.', fullDescription: 'Стань востребованным QA-инженером.', studyDuration: 6, price: '48 000 ₽', category: 'adults-filter', tag: 'testing', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('QA'), teachers: generateTeachers('a1'), faq: generateFaq('QA') },
    { id: 'a2', title: 'Digital Marketing', shortDescription: 'Управляй трафиком.', fullDescription: 'Комплексный курс по маркетингу.', studyDuration: 4, price: '32 000 ₽', category: 'adults-filter', tag: 'marketing', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Marketing'), teachers: generateTeachers('a2'), faq: generateFaq('Marketing') },
    { id: 'a3', title: 'VR/AR Developer', shortDescription: 'Метавселенные.', fullDescription: 'Разработка виртуальной реальности.', studyDuration: 9, price: '45 000 ₽', category: 'adults-filter', tag: 'unity', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('VR/AR'), teachers: generateTeachers('a3'), faq: generateFaq('VR/AR') },
    { id: 'a4', title: 'Java Architect', shortDescription: 'Enterprise системы.', fullDescription: 'Проектирование сложных платформ.', studyDuration: 18, price: '75 000 ₽', category: 'adults-filter', tag: 'java', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Java Architect'), teachers: generateTeachers('a4'), faq: generateFaq('Java Architect') },
    { id: 'a5', title: 'Product UI/UX', shortDescription: 'Дизайн систем.', fullDescription: 'Дизайн для крупных продуктов.', studyDuration: 7, price: '38 000 ₽', category: 'adults-filter', tag: 'design', level: 'intermediate', type: 'course', background: getRandomColors(), benefits: generateBenefits('Product Design'), teachers: generateTeachers('a5'), faq: generateFaq('Product Design') },
    { id: 'a6', title: 'Python DS Pro', shortDescription: 'Data Science.', fullDescription: 'Анализ данных и нейросети.', studyDuration: 12, price: '58 000 ₽', category: 'adults-filter', tag: 'python', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('Data Science'), teachers: generateTeachers('a6'), faq: generateFaq('Data Science') },
    { id: 'a7', title: 'SEO Lead', shortDescription: 'Топ в Google.', fullDescription: 'Вывод сайтов на первые позиции.', studyDuration: 3, price: '20 000 ₽', category: 'adults-filter', tag: 'marketing', level: 'intermediate', type: 'special', background: getRandomColors(), benefits: generateBenefits('SEO'), teachers: generateTeachers('a7'), faq: generateFaq('SEO') },
    { id: 'a8', title: 'Manual QA', shortDescription: 'Старт в тестировании.', fullDescription: 'Ручное тестирование с нуля.', studyDuration: 2, price: '15 000 ₽', category: 'adults-filter', tag: 'testing', level: 'novice', type: 'course', background: getRandomColors(), benefits: generateBenefits('Manual QA'), teachers: generateTeachers('a8'), faq: generateFaq('Manual QA') },
    { id: 'a9', title: 'Node.js Backend', shortDescription: 'JS Сервер.', fullDescription: 'Разработка на JavaScript со стороны сервера.', studyDuration: 10, price: '42 000 ₽', category: 'adults-filter', tag: 'software', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Node.js'), teachers: generateTeachers('a9'), faq: generateFaq('Node.js') },
    { id: 'a10', title: 'iOS Lead', shortDescription: 'Управление командой.', fullDescription: 'Комплексная разработка под Apple.', studyDuration: 15, price: '65 000 ₽', category: 'adults-filter', tag: 'ios', level: 'pro', type: 'profession', background: getRandomColors(), benefits: generateBenefits('iOS Lead'), teachers: generateTeachers('a10'), faq: generateFaq('iOS Lead') },
    { id: 'a11', title: 'Enterprise Spring', shortDescription: 'Microservices.', fullDescription: 'Сложные системы на Spring Boot.', studyDuration: 11, price: '50 000 ₽', category: 'adults-filter', tag: 'java', level: 'pro', type: 'course', background: getRandomColors(), benefits: generateBenefits('Spring'), teachers: generateTeachers('a11'), faq: generateFaq('Spring') },
    { id: 'a12', title: 'UX Research', shortDescription: 'Поведение юзера.', fullDescription: 'Исследования и аналитика.', studyDuration: 2, price: '12 000 ₽', category: 'adults-filter', tag: 'design', level: 'novice', type: 'special', background: getRandomColors(), benefits: generateBenefits('Research'), teachers: generateTeachers('a12'), faq: generateFaq('Research') },
];